### ISSUE TITLE
Fix typo in repository name

### ISSUE THREAD

**Issue by gmacario** [GENIVI/open-adress-book#2]
As PR https://github.com/GENIVI/open-adress-book/pull/1 was accepted we should fix the name of the git repository as well (from https://github.com/GENIVI/open-adress-book to https://github.com/GENIVI/open-address-book)

**Comment by jeremiah** [comment]
Yeah, sorry. I created this typo (I used the Swedish spelling for address.) The maintainer has to change the name because it affects internal repositories.

**Comment by dmbuckle** [comment]
Hi. I agree it needs to be changed. But I do not have permissions/privileges to do so. 
- Only members with owner privileges for an organization or admin privileges for a repository can rename a repository. For more information, see "Repository permission levels for an organization."

**Comment by jeremiah** [comment]
Let me give you those permissions . . .

**Comment by jeremiah** [comment]
I changed your access to "maintainer" and I made sure maintainers can make changes to the team repos, of which there is only one, OAD.

**Comment by dmbuckle** [comment]
Done!
